spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_dev
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update   # later: validate (with Flyway)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect